const fs = require('fs');
const path = require('path');

function parseEnvFile(filePath) {
    if (!fs.existsSync(filePath)) return {};

    const raw = fs.readFileSync(filePath, 'utf8');
    const lines = raw.split(/\r?\n/);
    const values = {};

    for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;

        const eqIndex = trimmed.indexOf('=');
        if (eqIndex <= 0) continue;

        const key = trimmed.slice(0, eqIndex).trim();
        let value = trimmed.slice(eqIndex + 1).trim();

        if (
            (value.startsWith('"') && value.endsWith('"')) ||
            (value.startsWith("'") && value.endsWith("'"))
        ) {
            value = value.slice(1, -1);
        }

        values[key] = value;
    }

    return values;
}

function toLiteral(value) {
    return JSON.stringify(value);
}

function main() {
    const frontendRoot = path.resolve(__dirname, '..');
    const repoRoot = path.resolve(frontendRoot, '..');
    const envPath = path.join(frontendRoot, '.env');
    const outPath = path.join(frontendRoot, 'public', 'runtime-config.js');

    const env = {
        ...parseEnvFile(path.join(repoRoot, '.env')),
        ...parseEnvFile(path.join(repoRoot, 'backend', '.env')),
        ...parseEnvFile(envPath)
    };

    const backendPort = Number.parseInt(env.PORT || '', 10);
    const apiPort = Number.parseInt(env.API_PORT || '', 10) || backendPort || 8000;
    const explicitApiUrl = env.API_URL || '';
    const runtimeConfig = {
        NODE_ENV: env.NODE_ENV || 'development',
        API_URL: explicitApiUrl || null,
        API_PORT: apiPort,
        MAP_TILES_URL: env.MAP_TILES_URL || '/tiles',
        PARK_NAME: env.PARK_NAME || 'Bwindi Impenetrable National Park',
        DEFAULT_LANGUAGE: env.DEFAULT_LANGUAGE || 'en'
    };

    const output = `// Auto-generated by scripts/generateRuntimeConfig.js
window.__SIGTS_CONFIG__ = ${toLiteral(runtimeConfig)};
(function() {
  var cfg = window.__SIGTS_CONFIG__ || {};
  var pageOrigin = window.location && window.location.origin ? window.location.origin : 'http://localhost:3000';
  var pagePort = window.location && window.location.port
    ? window.location.port
    : (window.location && window.location.protocol === 'https:' ? '443' : '80');

  // Port 3000 (live-server): talk to backend port directly — proxy strips /api prefix
  if (pagePort === '3000') {
    var apiPort3000 = Number(cfg.API_PORT) || 8000;
    var host3000 = window.location && window.location.hostname ? window.location.hostname : 'localhost';
    if (cfg.API_URL) {
      try {
        var parsed3000 = new URL(cfg.API_URL, pageOrigin);
        var apiHost3000 = parsed3000.hostname || '';
        if (host3000 && (apiHost3000 === 'localhost' || apiHost3000 === '127.0.0.1') && host3000 !== apiHost3000) {
          parsed3000.hostname = host3000;
        }
        var href3000 = parsed3000.toString().replace(/\\/$/, '');
        if (!/\\/api$/i.test(href3000)) href3000 = parsed3000.origin + '/api';
        window.__SIGTS_API_BASE__ = href3000;
        return;
      } catch (_) {
        window.__SIGTS_API_BASE__ = cfg.API_URL;
        return;
      }
    }
    window.__SIGTS_API_BASE__ = (window.location.protocol || 'http:') + '//' + host3000 + ':' + apiPort3000 + '/api';
    return;
  }

  if (pagePort === '80' || pagePort === '443' || pagePort === '') {
    window.__SIGTS_API_BASE__ = pageOrigin.replace(/\\/$/, '') + '/api';
    return;
  }

  if (cfg.API_URL) {
    try {
      var currentHost = window.location && window.location.hostname ? window.location.hostname : '';
      var parsed = new URL(cfg.API_URL, pageOrigin);
      var apiHost = parsed.hostname || '';
      var isLocalApiHost = apiHost === 'localhost' || apiHost === '127.0.0.1';
      if (currentHost && currentHost !== 'localhost' && currentHost !== '127.0.0.1' && isLocalApiHost) {
        parsed.hostname = currentHost;
      }
      var href = parsed.toString().replace(/\\/$/, '');
      if (!/\\/api$/i.test(href)) {
        href = parsed.origin + '/api';
      }
      window.__SIGTS_API_BASE__ = href;
      return;
    } catch (_) {
      window.__SIGTS_API_BASE__ = cfg.API_URL;
      return;
    }
  }
  var protocol = window.location && window.location.protocol ? window.location.protocol : 'http:';
  var hostname = window.location && window.location.hostname ? window.location.hostname : 'localhost';
  var port = Number(cfg.API_PORT) || 8000;
  window.__SIGTS_API_BASE__ = protocol + '//' + hostname + ':' + port + '/api';
})();
`;

    fs.writeFileSync(outPath, output, 'utf8');
    console.log(`Generated runtime config at ${outPath} (API port ${apiPort})`);
}

main();
