const fs = require('fs');
const path = require('path');

function parseEnvFile(filePath) {
    if (!fs.existsSync(filePath)) return {};

    const raw = fs.readFileSync(filePath, 'utf8');
    const lines = raw.split(/\r?\n/);
    const values = {};

    for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;

        const eqIndex = trimmed.indexOf('=');
        if (eqIndex <= 0) continue;

        const key = trimmed.slice(0, eqIndex).trim();
        let value = trimmed.slice(eqIndex + 1).trim();

        if (
            (value.startsWith('"') && value.endsWith('"')) ||
            (value.startsWith("'") && value.endsWith("'"))
        ) {
            value = value.slice(1, -1);
        }

        values[key] = value;
    }

    return values;
}

function toLiteral(value) {
    return JSON.stringify(value);
}

function main() {
    const frontendRoot = path.resolve(__dirname, '..');
    const envPath = path.join(frontendRoot, '.env');
    const outPath = path.join(frontendRoot, 'public', 'runtime-config.js');

    const env = parseEnvFile(envPath);
    const runtimeConfig = {
        NODE_ENV: env.NODE_ENV || 'development',
        API_URL: env.API_URL || 'http://localhost:8000/api',
        MAP_TILES_URL: env.MAP_TILES_URL || '/tiles',
        PARK_NAME: env.PARK_NAME || 'Bwindi Impenetrable National Park',
        DEFAULT_LANGUAGE: env.DEFAULT_LANGUAGE || 'en'
    };

    const output = `// Auto-generated by scripts/generateRuntimeConfig.js
window.__SIGTS_CONFIG__ = ${toLiteral(runtimeConfig)};
window.__SIGTS_API_BASE__ = window.__SIGTS_CONFIG__.API_URL;
`;

    fs.writeFileSync(outPath, output, 'utf8');
    console.log(`Generated runtime config at ${outPath}`);
}

main();
