const fs = require('fs');
const path = require('path');

function parseEnvFile(filePath) {
    if (!fs.existsSync(filePath)) return {};

    const raw = fs.readFileSync(filePath, 'utf8');
    const lines = raw.split(/\r?\n/);
    const values = {};

    for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;

        const eqIndex = trimmed.indexOf('=');
        if (eqIndex <= 0) continue;

        const key = trimmed.slice(0, eqIndex).trim();
        let value = trimmed.slice(eqIndex + 1).trim();

        if (
            (value.startsWith('"') && value.endsWith('"')) ||
            (value.startsWith("'") && value.endsWith("'"))
        ) {
            value = value.slice(1, -1);
        }

        values[key] = value;
    }

    return values;
}

function toLiteral(value) {
    return JSON.stringify(value);
}

function main() {
    const frontendRoot = path.resolve(__dirname, '..');
    const envPath = path.join(frontendRoot, '.env');
    const outPath = path.join(frontendRoot, 'public', 'runtime-config.js');

    const env = parseEnvFile(envPath);
    const apiPort = Number.parseInt(env.API_PORT || '', 10) || 8001;
    const explicitApiUrl = env.API_URL || '';
    const runtimeConfig = {
        NODE_ENV: env.NODE_ENV || 'development',
        API_URL: explicitApiUrl || null,
        API_PORT: apiPort,
        MAP_TILES_URL: env.MAP_TILES_URL || '/tiles',
        PARK_NAME: env.PARK_NAME || 'Bwindi Impenetrable National Park',
        DEFAULT_LANGUAGE: env.DEFAULT_LANGUAGE || 'en'
    };

    const output = `// Auto-generated by scripts/generateRuntimeConfig.js
window.__SIGTS_CONFIG__ = ${toLiteral(runtimeConfig)};
(function() {
  var cfg = window.__SIGTS_CONFIG__ || {};
  if (cfg.API_URL) {
    try {
      var currentHost = window.location && window.location.hostname ? window.location.hostname : '';
      var parsed = new URL(cfg.API_URL, window.location ? window.location.origin : 'http://localhost');
      var apiHost = parsed.hostname || '';
      var isLocalApiHost = apiHost === 'localhost' || apiHost === '127.0.0.1';
      if (currentHost && currentHost !== 'localhost' && currentHost !== '127.0.0.1' && isLocalApiHost) {
        parsed.hostname = currentHost;
      }
      window.__SIGTS_API_BASE__ = parsed.toString().replace(/\/$/, '');
      return;
    } catch (_) {
      window.__SIGTS_API_BASE__ = cfg.API_URL;
      return;
    }
  }
  var protocol = window.location && window.location.protocol ? window.location.protocol : 'http:';
  var hostname = window.location && window.location.hostname ? window.location.hostname : 'localhost';
  var port = Number(cfg.API_PORT) || 8001;
  window.__SIGTS_API_BASE__ = protocol + '//' + hostname + ':' + port + '/api';
})();
`;

    fs.writeFileSync(outPath, output, 'utf8');
    console.log(`Generated runtime config at ${outPath}`);
}

main();
